In [2]:
import torch
import numpy as np

In [3]:
a = torch.randn(5, requires_grad=True)
ab = ((a + 2) ** 2).sum()
ab.backward()
print(a.grad)

tensor([2.4303, 3.3933, 2.7869, 3.4342, 3.6275])


In [4]:
x = torch.tensor([.13,0.015,0.17], requires_grad=True, dtype=torch.float32)
y = x*6
z = y*y/2
z = z.mean()
print(z)

z.backward()
print(z)
print(x.grad)

tensor(0.2761, grad_fn=<MeanBackward0>)
tensor(0.2761, grad_fn=<MeanBackward0>)
tensor([1.5600, 0.1800, 2.0400])


Stopping pytorch from tracking gradient

In [8]:
x = torch.tensor([.13,0.015,0.17], requires_grad=True, dtype=torch.float32)

x.requires_grad_(False)  #disables grading tracking
y = x**2

print(x)
print(y)

tensor([0.1300, 0.0150, 0.1700])
tensor([0.0169, 0.0002, 0.0289])


In [9]:
x = torch.tensor([.13,0.015,0.17], requires_grad=True, dtype=torch.float32)
y = x.detach()
print(y)

tensor([0.1300, 0.0150, 0.1700])


In [10]:
x = torch.tensor([.13,0.015,0.17], requires_grad=True, dtype=torch.float32)
with torch.no_grad():
    y = x + 2
    print(y)

tensor([2.1300, 2.0150, 2.1700])


In [20]:
weights = torch.ones(4, requires_grad=True)
for epoch in range(3):
    model_output = (weights*5).sum()
    model_output.backward() #accumulates the previous values in grad attribute as many times as called
    print(weights.grad)
    
    #accumulations results in incorrect gradient with each epoch

tensor([5., 5., 5., 5.])
tensor([10., 10., 10., 10.])
tensor([15., 15., 15., 15.])


In [21]:
weights = torch.ones(4, requires_grad=True)
for epoch in range(3):
    model_output = (weights*5).sum()
    model_output.backward() 
    print(weights.grad)
    weights.grad.zero_()  #empties gradient, hence avoiding acculumation
    
#doesnot accumulate here, so sorrect!

tensor([5., 5., 5., 5.])
tensor([5., 5., 5., 5.])
tensor([5., 5., 5., 5.])
