In [44]:
import torch
import numpy as np

In [45]:
x = torch.empty(1)   #tensor of shape 1
y = torch.empty(5)   #tensor of shape 5
print("x is {}".format(x))
print("y is {}".format(y))

x is tensor([4.8347e+19])
y is tensor([4.8347e+19, 4.5628e-41, 4.1367e-23, 3.0798e-41, 4.4842e-44])


In [46]:
x = torch.empty(2,3)   #tensor of shape (2,3)
print("x is {}".format(x))
print("Dtype of x is {}".format(x.dtype))  #by default float32

print()

y = torch.empty(2,3,2)   #tensor of shape (2,3,2)
print("y is {}".format(y))

x is tensor([[4.8347e+19, 4.5628e-41, 4.0833e-23],
        [3.0798e-41, 4.4842e-44, 0.0000e+00]])
Dtype of x is torch.float32

y is tensor([[[0.0000e+00, 0.0000e+00],
         [4.2079e-23, 3.0798e-41],
         [6.1972e-04, 7.2443e+22]],

        [[1.7728e+28, 7.0367e+22],
         [1.5471e-04, 2.1748e+23],
         [1.3028e-11, 2.6563e+20]]])


In [47]:
x = torch.rand(2,2)   #random
print("x is {}".format(x))

print()

y = torch.zeros(3,3)    #zeros
print("y is {}".format(y))

print()

z = torch.ones(3,3)   #ones
print("z is {}".format(z))

print()

z2 = torch.ones(3,3)*2   #multiplying constant with tensor
print("z*2 is {}".format(z2))

print()

z3 = torch.ones(3,3) + 3   #adding constant to tensor
print("z+3 is {}".format(z3))

x is tensor([[0.3471, 0.5315],
        [0.1641, 0.0436]])

y is tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

z is tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

z*2 is tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])

z+3 is tensor([[4., 4., 4.],
        [4., 4., 4.],
        [4., 4., 4.]])


In [48]:
z = torch.ones(3,3, dtype=torch.double) #ones but in double dtype
print("z is {}".format(z))

z = torch.ones(3,3, dtype=torch.float32) #ones but in float32 dtype (default)
print("z is {}".format(z))

z = torch.ones(3,3, dtype=torch.float16) #ones but in float16 dtype
print("z is {}".format(z))

z = torch.ones(3,3, dtype=torch.int) #ones but in int dtype
print("z is {}".format(z))

z is tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
z is tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
z is tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float16)
z is tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)


In [49]:
x= torch.tensor([1,3,4,7])      #list to tensor
y = torch.tensor(np.array([[100,200],
                           [300,400]]))  #numpy array to tensor

print("x is {}".format(x))
print()
print("y is {}".format(y))

x is tensor([1, 3, 4, 7])

y is tensor([[100, 200],
        [300, 400]])


In [50]:
x= torch.ones(3,3)*2
y= torch.ones(3,3)+5
print("x is {}".format(x))
print("y is {}".format(y))

z1 = x + y     #elementwise addition
print("z1 is {}".format(z1))

z2 = x * y   #elementwise multiplication
print("z2 is {}".format(z2))

z3 = x / y   #elementwise divisiion
print("z3 is {}".format(z3))

x is tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])
y is tensor([[6., 6., 6.],
        [6., 6., 6.],
        [6., 6., 6.]])
z1 is tensor([[8., 8., 8.],
        [8., 8., 8.],
        [8., 8., 8.]])
z2 is tensor([[12., 12., 12.],
        [12., 12., 12.],
        [12., 12., 12.]])
z3 is tensor([[0.3333, 0.3333, 0.3333],
        [0.3333, 0.3333, 0.3333],
        [0.3333, 0.3333, 0.3333]])


In [51]:
x= torch.ones(3,3)*2
y= torch.ones(3,3)+5
print("x is {}".format(x))
print("y is {}".format(y))

print("Addition= {}".format(torch.add(x,y)))
print("Subtraction= {}".format(torch.sub(x,y)))   #sub or subtract (x-y)
print("Multiplication= {}".format(torch.mul(x,y)))  #mul or multiply (x*y)
print("Division= {}".format(torch.div(x,y)))   #div or divide (x/y)

x is tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])
y is tensor([[6., 6., 6.],
        [6., 6., 6.],
        [6., 6., 6.]])
Addition= tensor([[8., 8., 8.],
        [8., 8., 8.],
        [8., 8., 8.]])
Subtraction= tensor([[-4., -4., -4.],
        [-4., -4., -4.],
        [-4., -4., -4.]])
Multiplication= tensor([[12., 12., 12.],
        [12., 12., 12.],
        [12., 12., 12.]])
Division= tensor([[0.3333, 0.3333, 0.3333],
        [0.3333, 0.3333, 0.3333],
        [0.3333, 0.3333, 0.3333]])


In [52]:
x= torch.ones(3,3)*2
y= torch.ones(3,3)+5
print("x is {}".format(x))
print("y is {}".format(y))

y.add_(x)  #same as y=y+x
print("Modified (added) y = {}".format(y))

y.sub_(x)   #same as y=y-x
print("Modified (subtracted) y = {}".format(y))

y.multiply_(x)    #same as y=y*x
print("Modified (multiplied) y = {}".format(y))

y.divide_(x)   #same as y=y/x
print("Modified (divided) y = {}".format(y))


#In pytorch, every function with a trailing underscore means
#in place operation

x is tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])
y is tensor([[6., 6., 6.],
        [6., 6., 6.],
        [6., 6., 6.]])
Modified (added) y = tensor([[8., 8., 8.],
        [8., 8., 8.],
        [8., 8., 8.]])
Modified (subtracted) y = tensor([[6., 6., 6.],
        [6., 6., 6.],
        [6., 6., 6.]])
Modified (multiplied) y = tensor([[12., 12., 12.],
        [12., 12., 12.],
        [12., 12., 12.]])
Modified (divided) y = tensor([[6., 6., 6.],
        [6., 6., 6.],
        [6., 6., 6.]])


In [53]:
x= torch.ones(3,3)*2
y= torch.ones(3,3)+5
print("x is {}".format(x))
print("y is {}".format(y))

y+= x   #similiarly -,*,/
print(y)

x is tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])
y is tensor([[6., 6., 6.],
        [6., 6., 6.],
        [6., 6., 6.]])
tensor([[8., 8., 8.],
        [8., 8., 8.],
        [8., 8., 8.]])


In [54]:
x = torch.rand(4,6)
print(x)
print("All rows of 3rd column: {}".format(x[:,3]))    #slicing like in numpy
print("All rows of 1st two columns: {}".format(x[:,:2]))
print("All rows of last 3 columns: {}".format(x[:,-3:]))

tensor([[0.0166, 0.0026, 0.4487, 0.4051, 0.0920, 0.3154],
        [0.4272, 0.3169, 0.1220, 0.7611, 0.9726, 0.0172],
        [0.1619, 0.5159, 0.3348, 0.9502, 0.8911, 0.1126],
        [0.0018, 0.5167, 0.8047, 0.1858, 0.6685, 0.1531]])
All rows of 3rd column: tensor([0.4051, 0.7611, 0.9502, 0.1858])
All rows of 1st two columns: tensor([[0.0166, 0.0026],
        [0.4272, 0.3169],
        [0.1619, 0.5159],
        [0.0018, 0.5167]])
All rows of last 3 columns: tensor([[0.4051, 0.0920, 0.3154],
        [0.7611, 0.9726, 0.0172],
        [0.9502, 0.8911, 0.1126],
        [0.1858, 0.6685, 0.1531]])


In [55]:
x = torch.rand(3,4)
print(x)
print(x[2,2])
print(x[2,2].item()) #item()off used only if 1 value is to be needed

tensor([[0.8841, 0.8726, 0.0025, 0.3829],
        [0.3967, 0.2685, 0.5994, 0.4515],
        [0.1186, 0.3646, 0.9400, 0.1757]])
tensor(0.9400)
0.9400306940078735


In [56]:
x= torch.rand(4,3)
print(x)
print(x.view(6,2))  #reshaped into 6,2
print(x.view(12))   #reshaped into 12

tensor([[0.1374, 0.0833, 0.4008],
        [0.7791, 0.6841, 0.6387],
        [0.3925, 0.9040, 0.0437],
        [0.0827, 0.5843, 0.6257]])
tensor([[0.1374, 0.0833],
        [0.4008, 0.7791],
        [0.6841, 0.6387],
        [0.3925, 0.9040],
        [0.0437, 0.0827],
        [0.5843, 0.6257]])
tensor([0.1374, 0.0833, 0.4008, 0.7791, 0.6841, 0.6387, 0.3925, 0.9040, 0.0437,
        0.0827, 0.5843, 0.6257])


In [62]:
x= torch.rand(4,3)
print(x)
y= x.view(-1,2)   #when one or more dimension is unknown
print(y)
print(y.size())

tensor([[0.5091, 0.1322, 0.1978],
        [0.6767, 0.5865, 0.8729],
        [0.2511, 0.4143, 0.6833],
        [0.1164, 0.6754, 0.4538]])
tensor([[0.5091, 0.1322],
        [0.1978, 0.6767],
        [0.5865, 0.8729],
        [0.2511, 0.4143],
        [0.6833, 0.1164],
        [0.6754, 0.4538]])
torch.Size([6, 2])


In [65]:
x = torch.rand(3,5)
y = x.numpy()   #tensor to numpy
print(y)
print(type(y))

[[0.15802383 0.69605887 0.7722925  0.9849919  0.47540933]
 [0.8993654  0.09174275 0.42777014 0.98152095 0.610631  ]
 [0.27357632 0.13028634 0.93119115 0.42569518 0.6692621 ]]
<class 'numpy.ndarray'>


In [67]:
x = torch.zeros(3,5)
y = x.numpy()   #torch to numpy

x.add_(1)  #y is also added to 1
print(y)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [73]:
y = np.zeros((3,3))
x = torch.from_numpy(y)  #numpy to torch
print(x)

y+=1     #x also gets added to one
print(x)


tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
